version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:7.4.2
    environment:
      - "discovery.type=single-node"
    networks:
      - elasticnet
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:7.4.2
    networks:
      - elasticnet
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  db:
    image: mysql:8.0.18
    environment:
    - "MYSQL_ROOT_PASSWORD=my-secret-pw"
    - "MYSQL_DATABASE=oerhoernchen_db"
    - "MYSQL_USER=oerhoernchen"
    - "MYSQL_PASSWORD=oerhoernchenpw"
    networks: 
      - elasticnet
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - "dbdata:/var/lib/mysql"

  logstash:
    build:
      context: ./logstash_mysql
      dockerfile: logstash_mysql.Dockerfile
    # volumes:
    #   - './logstash_mysql/config/logstash.conf:/usr/share/logstash/config/logstash.conf'
    ports:
      - "5001:5001"
      - "5044:5044"
      - "9600:9600"
    networks:
      - elasticnet
    depends_on:
      - elasticsearch
      - db
      - kibana

networks:
  elasticnet:

volumes:
  dbdata: